---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: true

provisioner:
  name: chef_zero
  data_bags_path: ./test/data_bags

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[postgresql::server]
      - recipe[pgbarman::default]
    attributes:
      postgresql:
        password:
          postgres:
            lolpassword
  - name: server
    run_list:
      - recipe[pgbarman::server]
    attributes:
