#<% require 'kitchen-sync' %>
---
driver:
  name: docker
  use_sudo: false
  hostname: barman.local

provisioner:
  name: chef_zero
  data_bags_path: ./test/data_bags

platforms:
  - name: centos-6
    driver_config:
       image: centos:6
       provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  - name: debian-squeeze
    driver_config:
      image: debian:squeeze
      provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  - name: debian-wheezy
    driver_config:
      image: debian:wheezy
      provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  - name: ubuntu-14
    driver_config:
      image: ubuntu:14.04
      provision_command: curl -L https://www.opscode.com/chef/install.sh | bash

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[pgbarman::default]
      - recipe[pgbarman::server]
    attributes:
