---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[pgbarman::default]
    attributes:
  - name: client
    run_list:
      - recipe[postgresql::server]
      - recipe[pgbarman::client]
    attributes:
      postgresql:
        password:
          postgres:
            lolpassword
