#<% require 'kitchen-sync' %>
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  data_bags_path: ./test/data_bags

platforms:
  - name: centos-6
    driver_config:
       image: centos:6
       provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  - name: centos-7
    driver_config:
       image: centos:7
       provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  - name: debian-wheezy
    driver_config:
      image: debian:wheezy
      provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  - name: debian-jessie
    driver_config:
      image: debian:jessie
      provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  - name: ubuntu-14
    driver_config:
      image: ubuntu:14.04
      provision_command: curl -L https://www.opscode.com/chef/install.sh | bash

suites:
  - name: default
    run_list:
      - recipe[locales]
      - recipe[postgresql::server]
      - recipe[pgbarman::default]
      - recipe[pgbarman::server]
    attributes:
      postgresql:
        password:
          postgres:
            lolpassword
